### PR TITLE
feat: add support and testing for ForwardDiff

### PR DESCRIPTION
**Pull request by jmurphy6895**
Added support for Forward Autodiff capabilities in the atmospheric models. I *think this should be the last PR in this effort.

### CODE REVIEW

**Comment by ronisbr** [comment]
Awesome! Thanks @jmurphy6895 for this amazing work!

**Comment by ronisbr** [comment]
Hi @jmurphy6895 !

I did not forget the PRs. I just had personal problems and I still did not have time to test them. I will try to do this by the weekend. Sorry about the delay.

**Comment by JRock95** [comment]
Hey @ronisbr, no worries! This isn't a blocker for the next step or two for me so no rush. Just whenever you get a chance!

**Comment by ronisbr** [comment]
Thanks @jmurphy6895 !

**Pull request merged**
